/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import { useFetchMutator } from '../../../api/index';



  export const getApiSseUserId = (
    userId: number,
 ) => {
      return useFetchMutator<void>(
      {url: `/api/sse/${userId}`, method: 'GET'
    },
      );
    }
  export const getApiSseStatus = (
    
 ) => {
      return useFetchMutator<void>(
      {url: `/api/sse/status`, method: 'GET'
    },
      );
    }
  export type GetApiSseUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiSseUserId>>>
export type GetApiSseStatusResult = NonNullable<Awaited<ReturnType<typeof getApiSseStatus>>>
