/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  CreateStarDto,
  Star
} from '../../models';

import { useFetchMutator } from '../../../api/index';



  /**
 * @summary Создание новой звезды
 */
export const postApiStar = (
    createStarDto: CreateStarDto,
 ) => {
      return useFetchMutator<Star>(
      {url: `/api/star`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStarDto
    },
      );
    }
  export type PostApiStarResult = NonNullable<Awaited<ReturnType<typeof postApiStar>>>
