/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  TechTreeDto
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  export const getApiTechGetTechTree = (
    
 ) => {
      return useFetchMutator<TechTreeDto>(
      {url: `/api/tech/get-tech-tree`, method: 'GET'
    },
      );
    }
  export type GetApiTechGetTechTreeResult = NonNullable<Awaited<ReturnType<typeof getApiTechGetTechTree>>>
