/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  TechTreeDto,
  Technology
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  /**
 * @summary Получение полного дерева технологий для отрисовки на клиенте
 */
export const getApiTechGetTechTree = (
    
 ) => {
      return useFetchMutator<TechTreeDto>(
      {url: `/api/tech/get-tech-tree`, method: 'GET'
    },
      );
    }
  /**
 * @summary Получение технологии по techInnerId
 */
export const getApiTechTechInnerId = (
    techInnerId: number,
 ) => {
      return useFetchMutator<Technology>(
      {url: `/api/tech/${techInnerId}`, method: 'GET'
    },
      );
    }
  export type GetApiTechGetTechTreeResult = NonNullable<Awaited<ReturnType<typeof getApiTechGetTechTree>>>
export type GetApiTechTechInnerIdResult = NonNullable<Awaited<ReturnType<typeof getApiTechTechInnerId>>>
