/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { Galaxy } from './galaxy';

export interface BlackHole {
  id?: number;
  coordinateX: number;
  coordinateY: number;
  horizonRadius: number;
  /** @nullable */
  galaxyId?: number | null;
  galaxy?: Galaxy;
}
