/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export type BuildingActionType = typeof BuildingActionType[keyof typeof BuildingActionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuildingActionType = {
  Construct: 'Construct',
  Demolish: 'Demolish',
} as const;
