/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { BuildingActionType } from './buildingActionType';

export interface BuildingQueue {
  id?: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  buildingType: string;
  actionType: BuildingActionType;
  count: number;
  readonly createdAt: string;
  readyAt: string;
}
