/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface BuildingNeedResources {
  id?: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  resourceName: string;
  amountPerTick: number;
  volumePerTick: number;
}
