/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface ChangeSpeedPercentForTechDto {
  userId: number;
  techInnerId: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  newEfficiency: number;
}
