/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface ChangeUserSettingsDto {
  userId: number;
  /** @nullable */
  setting: string | null;
  settingValue: boolean;
}
