/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface CitizensDto {
  maxCitizens?: number;
  currentCitizens?: number;
  consuming?: number;
  balance?: number;
  notEnoughCitizensPercent?: number;
  birthRate?: number;
}
