/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface CreateUserRequestDto {
  /** @nullable */
  nickName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}
