/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { BuildingActionType } from './buildingActionType';

export interface CreateBuildingDto {
  /** ID планеты */
  planetId: number;
  /**
   * Тип здания (Storage, Factory, Mine)
   * @minLength 0
   * @maxLength 100
   */
  buildingType: string;
  actionType: BuildingActionType;
  /**
   * Количество зданий для добавления
   * @minimum 1
   * @maximum 1000
   */
  count?: number;
}
