/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { GalaxyForm } from './galaxyForm';

export interface CreateGalaxyDto {
  form: GalaxyForm;
  /**
   * @minimum -1000
   * @maximum 1000
   */
  coordinateX: number;
  /**
   * @minimum -1000
   * @maximum 1000
   */
  coordinateY: number;
}
