/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { GalaxyForm } from './galaxyForm';

export interface CreateGalaxyDto {
  form?: GalaxyForm;
  coordinateX?: number;
  coordinateY?: number;
}
