/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export type GalaxyForm = typeof GalaxyForm[keyof typeof GalaxyForm];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GalaxyForm = {
  Spiral: 'Spiral',
  Elliptical: 'Elliptical',
  Irregular: 'Irregular',
  Lenticular: 'Lenticular',
} as const;
