/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { GalaxyForm } from './galaxyForm';
import type { BlackHole } from './blackHole';
import type { Star } from './star';

export interface Galaxy {
  id?: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  radius: number;
  form: GalaxyForm;
  coordinateX: number;
  coordinateY: number;
  centralBlackHoleId: number;
  centralBlackHole: BlackHole;
  /** @nullable */
  stars?: Star[] | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
