/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { GetBuildingInfoDto } from './getBuildingInfoDto';

export interface GameBuildingsResponseDto {
  common: GetBuildingInfoDto[];
  complex: GetBuildingInfoDto[];
  energy: GetBuildingInfoDto[];
  factory: GetBuildingInfoDto[];
  food: GetBuildingInfoDto[];
  industrial: GetBuildingInfoDto[];
  mine: GetBuildingInfoDto[];
}
