/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { BuildingCanProduce } from './buildingCanProduce';
import type { BuildingNeedResources } from './buildingNeedResources';
import type { BuildingNeedMaterials } from './buildingNeedMaterials';

export interface GameBuildings {
  /**
   * @minLength 1
   * @maxLength 50
   */
  buildingType: string;
  /** Additional storage capacity provided by this building */
  capacity: number;
  /** Space consumed by this building */
  needSpace: number;
  /** Daily maintenance cost */
  amortization: number;
  /** Energy consumed per hour */
  needEnergy: number;
  /** Energy produced per hour */
  produceEnergy: number;
  sciencePowerBonus: number;
  foodProducePerDay: number;
  citizensBonus: number;
  birthRateBonus: number;
  /** @nullable */
  cost?: string | null;
  /**
   * @minLength 1
   * @maxLength 20
   */
  buildingClass: string;
  needCitizens: number;
  createdAt: string;
  /** @nullable */
  canProduces?: BuildingCanProduce[] | null;
  /** @nullable */
  needResources?: BuildingNeedResources[] | null;
  /** @nullable */
  needMaterials?: BuildingNeedMaterials[] | null;
}
