/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface GameBuildings {
  /**
   * @minLength 1
   * @maxLength 50
   */
  buildingType: string;
  /** Additional storage capacity provided by this building */
  capacity: number;
  /** Space consumed by this building */
  needSpace: number;
  /** Daily maintenance cost */
  amortization: number;
  /** Energy consumed per hour */
  needEnergy: number;
  /** Energy produced per hour */
  produceEnergy: number;
  foodProducePerDay: number;
  citizensBonus: number;
  birthRateBonus: number;
  /**
   * @minLength 1
   * @maxLength 20
   */
  buildingClass: string;
  needCitizens: number;
  createdAt: string;
}
