/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { GameBuildings } from './gameBuildings';

export interface GameBuildingsResponseDto {
  common: GameBuildings[];
  complex: GameBuildings[];
  energy: GameBuildings[];
  factory: GameBuildings[];
  food: GameBuildings[];
  industrial: GameBuildings[];
  mine: GameBuildings[];
}
