/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { BuildingCost } from './buildingCost';
import type { BuildingCanProduce } from './buildingCanProduce';
import type { BuildingNeedResources } from './buildingNeedResources';
import type { BuildingNeedMaterials } from './buildingNeedMaterials';

export interface GetBuildingInfoDto {
  /** @nullable */
  buildingType: string | null;
  /** @nullable */
  buildingClass: string | null;
  capacity: number;
  needSpace: number;
  amortization: number;
  needEnergy: number;
  produceEnergy: number;
  needCitizens: number;
  citizensBonus: number;
  birthRateBonus: number;
  foodProducePerDay: number;
  sciencePowerBonus: number;
  /** @nullable */
  cost: BuildingCost[] | null;
  createdAt: string;
  /** @nullable */
  canProduces: BuildingCanProduce[] | null;
  /** @nullable */
  needResources: BuildingNeedResources[] | null;
  /** @nullable */
  needMaterials: BuildingNeedMaterials[] | null;
}
