/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { BuildingCost } from './buildingCost';
import type { BuildingCanProduce } from './buildingCanProduce';
import type { BuildingNeedResources } from './buildingNeedResources';
import type { BuildingNeedMaterials } from './buildingNeedMaterials';

export interface GetBuildingInfoDto {
  /** @minLength 1 */
  buildingType: string;
  /** @minLength 1 */
  buildingClass: string;
  capacity: number;
  needSpace: number;
  amortization: number;
  needEnergy: number;
  produceEnergy: number;
  needCitizens: number;
  citizensBonus: number;
  birthRateBonus: number;
  foodProducePerDay: number;
  sciencePowerBonus: number;
  cost: BuildingCost[];
  createdAt: string;
  canProduces: BuildingCanProduce[];
  needResources: BuildingNeedResources[];
  needMaterials: BuildingNeedMaterials[];
}
