/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { PlanetBuilding } from './planetBuilding';
import type { BuildingQueue } from './buildingQueue';
import type { CitizensDto } from './citizensDto';
import type { TaxDto } from './taxDto';
import type { ElectricityDto } from './electricityDto';
import type { FoodDto } from './foodDto';
import type { ParametersDto } from './parametersDto';
import type { PlanetResources } from './planetResources';
import type { PlanetStorageDto } from './planetStorageDto';

export interface GetPlanetResponseDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  radius?: number;
  hasAtmosphere?: boolean;
  hasMagneticField?: boolean;
  isHomePlanet?: boolean;
  averageTemperature?: number;
  square?: number;
  freeSquare?: number;
  gravityPower?: number;
  distanceFromStar?: number;
  /** @nullable */
  planetOwnerId?: number | null;
  /** @nullable */
  buildings: PlanetBuilding[] | null;
  /** @nullable */
  buildingQueue: BuildingQueue[] | null;
  citizens?: CitizensDto;
  taxes?: TaxDto;
  electricity?: ElectricityDto;
  food?: FoodDto;
  parameters?: ParametersDto;
  planetResources: PlanetResources;
  storage?: PlanetStorageDto;
  isStorageOverflow?: boolean;
}
