/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { RequiredTech } from './requiredTech';
import type { TechnologyBonus } from './technologyBonus';

export interface GetTechInfoForUserDto {
  innerId: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  currentLearnedLevel: number;
  maxAvailableLevelToLearn: number;
  /** @nullable */
  requiredTeches: RequiredTech[] | null;
  /** @nullable */
  bonuses: TechnologyBonus[] | null;
}
