/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { RequiredTech } from './requiredTech';
import type { TechnologyBonus } from './technologyBonus';

export interface IBaseTechnology {
  readonly innerId?: number;
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly description?: string | null;
  readonly cost?: number;
  /** @nullable */
  readonly line?: string | null;
  readonly deep?: number;
  /** @nullable */
  readonly requiredTeches?: readonly RequiredTech[] | null;
  /** @nullable */
  bonuses?: TechnologyBonus[] | null;
}
