/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { PlanetIndustriesDtoItem } from './planetIndustriesDtoItem';
import type { PlanetIndustriesDtoBalance } from './planetIndustriesDtoBalance';

export interface PlanetIndustriesDto {
  mines: PlanetIndustriesDtoItem[];
  factories: PlanetIndustriesDtoItem[];
  industries: PlanetIndustriesDtoItem[];
  complexes: PlanetIndustriesDtoItem[];
  balance: PlanetIndustriesDtoBalance;
}
