/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface PlanetResources {
  clay?: number;
  limestone?: number;
  iron?: number;
  coal?: number;
  boron?: number;
  nickel?: number;
  copper?: number;
  molybdenum?: number;
  vanadium?: number;
  oil?: number;
  titanium?: number;
  magnesium?: number;
  uranium?: number;
}
