/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { PlanetStorage } from './planetStorage';
import type { PlanetResources } from './planetResources';
import type { PlanetBuilding } from './planetBuilding';
import type { BuildingQueue } from './buildingQueue';
import type { User } from './user';

export interface Planet {
  id?: number;
  isStorageOverflow?: boolean;
  starId: number;
  galaxyId: number;
  foodProduction?: number;
  foodConsumption?: number;
  foodDelta?: number;
  energyDelta?: number;
  energyProduction?: number;
  energyConsumption?: number;
  sciencePower?: number;
  notEnoughEnergyPercent?: number;
  maxCitizens?: number;
  currentCitizens?: number;
  citizenConsumption?: number;
  citizenDelta?: number;
  birthRate?: number;
  notEnoughCitizenPercent?: number;
  taxProduction?: number;
  taxConsumption?: number;
  taxDelta?: number;
  buildingsAmortization?: number;
  readonly storeCapacity?: number;
  readonly planetManpower?: number;
  /**
   * Items stored on this planet
   * @nullable
   */
  storage?: PlanetStorage[] | null;
  planetResources?: PlanetResources;
  /**
   * @minLength 1
   * @maxLength 100
   */
  readonly name: string;
  /**
   * Buildings on this planet with counts
   * @nullable
   */
  planetBuildings?: PlanetBuilding[] | null;
  /**
   * Buildings currently in construction queue
   * @nullable
   */
  buildingQueue?: BuildingQueue[] | null;
  /**
   * @minimum 10000
   * @maximum 40000
   */
  radius: number;
  hasAtmosphere: boolean;
  hasTransportNetwork?: boolean;
  hasMagneticField: boolean;
  isHomePlanet: boolean;
  /**
   * @minimum -270
   * @maximum 400
   */
  readonly averageTemperature: number;
  hasActiveProductions?: boolean;
  readonly square: number;
  readonly freeSquare?: number;
  readonly buildSpeed: number;
  /**
   * @minimum 1
   * @maximum 6
   */
  readonly gravityPower: number;
  /**
   * @minimum 1
   * @maximum 30
   */
  distanceFromStar: number;
  /** @nullable */
  planetOwnerId?: number | null;
  planetOwner?: User;
}
