/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { PlanetIndustriesDtoBalance } from './planetIndustriesDtoBalance';

export interface PlanetIndustriesDto {
  /** @nullable */
  mines: unknown[] | null;
  /** @nullable */
  factories: unknown[] | null;
  /** @nullable */
  industries: unknown[] | null;
  /** @nullable */
  complexes: unknown[] | null;
  /** @nullable */
  balance: PlanetIndustriesDtoBalance;
}
