/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { StorageCapacityDto } from './storageCapacityDto';
import type { StorageItemDto } from './storageItemDto';

export interface PlanetStorageDto {
  capacity?: StorageCapacityDto;
  /** @nullable */
  resources?: StorageItemDto[] | null;
  /** @nullable */
  materials?: StorageItemDto[] | null;
  /** @nullable */
  metaMaterials?: StorageItemDto[] | null;
  /** @nullable */
  components?: StorageItemDto[] | null;
}
