/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { PlanetIndustriesCanProduce } from './planetIndustriesCanProduce';

export interface PlanetIndustriesDtoItem {
  count: number;
  /** @minLength 1 */
  buildingType: string;
  efficiency: number;
  canProduce: PlanetIndustriesCanProduce[];
  needResources: PlanetIndustriesCanProduce[];
  needMaterials: PlanetIndustriesCanProduce[];
  nextProductionTime: string;
}
