/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type PlanetIndustriesDtoBalance = {[key: string]: number} | null;
