/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface PlanetBuilding {
  /** Last time when this building produced resources */
  lastProductionTime: string;
  /** Next time when this building will produce resources */
  nextProductionTime: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  readonly buildingClass: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  buildingType: string;
  efficiency: number;
  maxEfficiency: number;
  count: number;
}
