/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface PlanetStorage {
  id?: number;
  planetId: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  groupType: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  itemType: string;
  amount: number;
  updatedAt: string;
}
