/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { User } from './user';

export interface PlayerResource {
  /** Reference to user */
  userId?: number;
  /**
   * Type of resource
   * @minLength 1
   * @maxLength 50
   */
  resourceType: string;
  /** Current amount of resource */
  amount: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  groupType: string;
  /** Date and time when resource was last updated */
  updatedAt: string;
  user?: User;
  readonly totalVolume?: number;
}
