/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface RefreshTokenResponse {
  /** @nullable */
  accessToken: string | null;
  /** @nullable */
  refreshToken: string | null;
}
