/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface RemoveFromPlanetStoreDto {
  userId: number;
  planetId: number;
  /** @nullable */
  gameItemType: string | null;
  amount?: number;
}
