/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface RemoveFromQueueDto {
  planetId?: number;
  /** @nullable */
  buildingType: string | null;
  amount: number;
}
