/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { ResourceItemDto } from './resourceItemDto';

/**
 * @nullable
 */
export type SharedResourcesResponseDtoMetaMaterials = {[key: string]: ResourceItemDto} | null;
