/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { SharedResourcesResponseDtoResources } from './sharedResourcesResponseDtoResources';
import type { SharedResourcesResponseDtoMaterials } from './sharedResourcesResponseDtoMaterials';
import type { SharedResourcesResponseDtoMetaMaterials } from './sharedResourcesResponseDtoMetaMaterials';
import type { SharedResourcesResponseDtoComponents } from './sharedResourcesResponseDtoComponents';

export interface SharedResourcesResponseDto {
  userId?: number;
  /** @nullable */
  resources?: SharedResourcesResponseDtoResources;
  /** @nullable */
  materials?: SharedResourcesResponseDtoMaterials;
  /** @nullable */
  metaMaterials?: SharedResourcesResponseDtoMetaMaterials;
  /** @nullable */
  components?: SharedResourcesResponseDtoComponents;
  maxStorage?: number;
  currentStorage?: number;
  storageUsagePercent?: number;
  isOverflow?: boolean;
}
