/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export type StarSize = typeof StarSize[keyof typeof StarSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarSize = {
  Tiny: 'Tiny',
  Dwarf: 'Dwarf',
  Normal: 'Normal',
  Giant: 'Giant',
  Supergiant: 'Supergiant',
} as const;
