/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export type StarGravityPower = typeof StarGravityPower[keyof typeof StarGravityPower];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarGravityPower = {
  VeryWeak: VeryWeak,
  Weak: Weak,
  Medium: Medium,
  Strong: Strong,
  VeryStrong: VeryStrong,
} as const;
