/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { StarType } from './starType';
import type { StarSize } from './starSize';
import type { StarGravityPower } from './starGravityPower';
import type { Galaxy } from './galaxy';
import type { Planet } from './planet';

export interface Star {
  id?: number;
  galaxyId: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  type: StarType;
  size: StarSize;
  coordinateX: number;
  coordinateY: number;
  readonly temperature: number;
  gravityRadius: number;
  gravityPower: StarGravityPower;
  age: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  galaxy?: Galaxy;
  /** @nullable */
  planets?: Planet[] | null;
}
