/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export type StarType = typeof StarType[keyof typeof StarType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarType = {
  YellowDwarf: YellowDwarf,
  OrangeDwarf: OrangeDwarf,
  RedDwarf: RedDwarf,
  BlueGiant: BlueGiant,
  WhiteDwarf: WhiteDwarf,
  NeutronStar: NeutronStar,
} as const;
