/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface StorageItemDto {
  /** @minLength 1 */
  type: string;
  amount: number;
  volume: number;
}
