/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface StorageItemDto {
  /** @nullable */
  type?: string | null;
  amount?: number;
}
