/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface TechEdge {
  /** @nullable */
  id: string | null;
  /** @nullable */
  source: string | null;
  /** @nullable */
  target: string | null;
}
