/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface TechRequirementDto {
  techId: number;
  techInnerId: number;
  /** @nullable */
  techName: string | null;
  requiredLevel: number;
}
