/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { TechnologyBonus } from './technologyBonus';
import type { RequiredTech } from './requiredTech';

export interface Technology {
  /** @nullable */
  bonuses?: TechnologyBonus[] | null;
  id?: number;
  innerId?: number;
  /**
   * @maxLength 300
   * @nullable
   */
  name: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  description: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  line: string | null;
  deep?: number;
  /** @nullable */
  bonusesJson?: string | null;
  cost: number;
  /** @nullable */
  requiredTechInnerIds?: number[] | null;
  /** @nullable */
  requiredTeches?: RequiredTech[] | null;
}
