/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface TechnologyQueue {
  id?: number;
  userId?: number;
  techInnerId?: number;
  targetLevel?: number;
  readyAt?: string;
  /**
   * @maxLength 50
   * @nullable
   */
  status?: string | null;
}
