/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface TechnologyQueue {
  id?: number;
  userId?: number;
  techInnerId?: number;
  targetLevel?: number;
  currentLevel?: number;
  startedAt?: string;
  readyAt?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  efficiency?: number;
  /**
   * @maxLength 50
   * @nullable
   */
  status?: string | null;
  sciencePowerSnapshot?: number;
  needScience?: number;
  scienceInvested?: number;
  lastUpdatedAt?: string;
}
