/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface TechnologyBonus {
  /** @nullable */
  bonusColumn: string | null;
  valuePerLevel: number;
  /** @nullable */
  description: string | null;
}
