/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { TechNode } from './techNode';
import type { TechEdge } from './techEdge';

export interface TechTreeDto {
  /** @nullable */
  nodes: TechNode[] | null;
  /** @nullable */
  edges: TechEdge[] | null;
}
