/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { TechRequirementDto } from './techRequirementDto';
import type { NodePosition } from './nodePosition';

export interface TechNode {
  id?: number;
  innerId?: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  costCoefficientPerLevel: number;
  cost: number;
  /** @nullable */
  requirements?: TechRequirementDto[] | null;
  position?: NodePosition;
}
