/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserResponseDto {
  id?: number;
  /** @nullable */
  nickName?: string | null;
  /** @nullable */
  email?: string | null;
  createdAt?: string;
  homePlanetId?: number;
  /** @nullable */
  spaceStationsIds?: number[] | null;
  /** @nullable */
  planetsIds?: number[] | null;
  /** @nullable */
  fleetsIds?: number[] | null;
  money?: number;
  sciencePower?: number;
  gameMoney?: number;
  subscriptionActive?: boolean;
  isAdmin?: boolean;
  isModerator?: boolean;
  /** @nullable */
  subscriptionExpiresAt?: string | null;
}
