/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { Planet } from './planet';
import type { UserTechnology } from './userTechnology';
import type { TechnologyQueue } from './technologyQueue';
import type { PlayerResource } from './playerResource';

export interface User {
  id?: number;
  /**
   * Unique username for the user
   * @minLength 1
   * @maxLength 50
   */
  nickName: string;
  /**
   * User's email address must be unique
   * @minLength 1
   * @maxLength 100
   */
  email: string;
  /**
   * Hashed password (min 10 characters)
   * @minLength 10
   * @maxLength 100
   */
  passwordHash: string;
  /** Date and time when user was created */
  createdAt?: string;
  /**
   * Reference to user's home planet
   * @nullable
   */
  homePlanetId?: number | null;
  homePlanet?: Planet;
  /**
   * Array of references to user's planets
   * @nullable
   */
  planetsIds?: number[] | null;
  /**
   * Array of references to user's space stations
   * @nullable
   */
  spaceStationsIds?: number[] | null;
  /**
   * Array of references to user's fleets
   * @nullable
   */
  fleetsIds?: number[] | null;
  /** User's regular currency */
  money?: number;
  /**
   * User's premium currency (up to 999,000,000,000)
   * @minimum 0
   * @maximum 999000000000
   */
  gameMoney?: number;
  /** Whether user's subscription is active */
  subscriptionActive?: boolean;
  /**
   * Date and time when subscription expires
   * @nullable
   */
  subscriptionExpiresAt?: string | null;
  /** Whether user has administrator privileges */
  isAdmin?: boolean;
  /** Whether user has moderator privileges */
  isModerator?: boolean;
  /** @nullable */
  technologies?: UserTechnology[] | null;
  /** @nullable */
  technologyQueue?: TechnologyQueue[] | null;
  /** Date and time of user's last activity */
  readonly lastActivityTime?: string;
  /**
   * User's global resources
   * @nullable
   */
  resources?: PlayerResource[] | null;
}
