/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserTechnology {
  id?: number;
  userId?: number;
  technologyId?: number;
  technologyInnerId?: number;
  level?: number;
}
