/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserSettings {
  userId: number;
  session_logs_hide_always: boolean;
  session_logs_close_on_click_outside: boolean;
  buildings_hide_info_on_build: boolean;
}
