/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserTechnologyQueueResponseDto {
  id?: number;
  userId?: number;
  techInnerId?: number;
  /** @nullable */
  techName: string | null;
  targetLevel?: number;
  efficiency?: number;
  scienceInvested?: number;
  needScience?: number;
  readyPercent: number;
  startedAt?: string;
  readyAt?: string;
  /** @nullable */
  status?: string | null;
}
