/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserTechnologyQueueCreateDto {
  userId: number;
  techInnerId: number;
  /** @nullable */
  status?: string | null;
  currentTechLevel: number;
  targetLevel: number;
}
