/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type { IBaseTechnology } from './iBaseTechnology';

export interface UserTechnologyDto {
  level?: number;
  technology: IBaseTechnology;
}
