/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */

export interface UserTechBonus {
  id?: number;
  userId: number;
  mineVolumeBonus?: number;
  mineSpeedBonus?: number;
}
