/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  CreateGalaxyDto,
  Galaxy
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  /**
 * Пример запроса:
            
    POST /api/galaxy
    {
        "form?": "Spiral",
    }
            
Доступные значения для form: Spiral, Elliptical, Irregular, Lenticular
 * @summary Создание новой галактики
 */
export const postApiGalaxy = (
    createGalaxyDto: CreateGalaxyDto,
 ) => {
      return useFetchMutator<Galaxy>(
      {url: `/api/galaxy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGalaxyDto
    },
      );
    }
  export type PostApiGalaxyResult = NonNullable<Awaited<ReturnType<typeof postApiGalaxy>>>
