/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  CreateUserRequestDto,
  CreateUserResponseDto,
  GetPlanetResponseDto,
  RemoveFromShareDto,
  SharedResourcesResponseDto
} from '../../models';

import { useFetchMutator } from '../../../api/index';



  /**
 * @summary Создание нового пользователя
 */
export const postApiUserCreate = (
    createUserRequestDto: CreateUserRequestDto,
 ) => {
      return useFetchMutator<CreateUserResponseDto>(
      {url: `/api/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequestDto
    },
      );
    }
  /**
 * @summary Получение общих ресурсов пользователя
 */
export const getApiUserGetSharedItemsUserId = (
    userId: number,
 ) => {
      return useFetchMutator<SharedResourcesResponseDto>(
      {url: `/api/user/get-shared-items/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Удаление из общего хранилища пользователя
 */
export const postApiUserRemoveSharedItem = (
    removeFromShareDto: RemoveFromShareDto,
 ) => {
      return useFetchMutator<void>(
      {url: `/api/user/remove-shared-item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeFromShareDto
    },
      );
    }
  /**
 * @summary Получение списка планет пользователя по userId
 */
export const getApiUserGetPlanetsUserId = (
    userId: number,
 ) => {
      return useFetchMutator<GetPlanetResponseDto[]>(
      {url: `/api/user/get-planets/${userId}`, method: 'GET'
    },
      );
    }
  export type PostApiUserCreateResult = NonNullable<Awaited<ReturnType<typeof postApiUserCreate>>>
export type GetApiUserGetSharedItemsUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetSharedItemsUserId>>>
export type PostApiUserRemoveSharedItemResult = NonNullable<Awaited<ReturnType<typeof postApiUserRemoveSharedItem>>>
export type GetApiUserGetPlanetsUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetPlanetsUserId>>>
