/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  ChangeUserSettingsDto,
  CreateUserRequestDto,
  CreateUserResponseDto,
  GetApiUserGetAllSettings200One,
  GetApiUserGetAllSettings200Three,
  GetApiUserGetAllSettings200Two,
  GetPlanetResponseDto,
  RemoveFromShareDto,
  SharedResourcesResponseDto,
  UserSettings
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  /**
 * @summary Создание нового пользователя
 */
export const postApiUserCreate = (
    createUserRequestDto: CreateUserRequestDto,
 ) => {
      return useFetchMutator<CreateUserResponseDto>(
      {url: `/api/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequestDto
    },
      );
    }
  /**
 * @summary Получение общих ресурсов пользователя
 */
export const getApiUserGetSharedItemsUserId = (
    userId: number,
 ) => {
      return useFetchMutator<SharedResourcesResponseDto>(
      {url: `/api/user/get-shared-items/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Удаление из общего хранилища пользователя
 */
export const postApiUserRemoveSharedItem = (
    removeFromShareDto: RemoveFromShareDto,
 ) => {
      return useFetchMutator<void>(
      {url: `/api/user/remove-shared-item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeFromShareDto
    },
      );
    }
  /**
 * @summary Получение списка планет пользователя по userId
 */
export const getApiUserGetPlanetsUserId = (
    userId: number,
 ) => {
      return useFetchMutator<GetPlanetResponseDto[]>(
      {url: `/api/user/get-planets/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Получение списка возможных настроек аккаунта
 */
export const getApiUserGetAllSettings = (
    
 ) => {
      return useFetchMutator<GetApiUserGetAllSettings200One | GetApiUserGetAllSettings200Two | GetApiUserGetAllSettings200Three>(
      {url: `/api/user/get-all-settings`, method: 'GET'
    },
      );
    }
  /**
 * @summary Получение списка настроек аккаунта по userId
 */
export const getApiUserGetUserSettingsUserId = (
    userId: number,
 ) => {
      return useFetchMutator<UserSettings[]>(
      {url: `/api/user/get-user-settings/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Изменение настроек аккаунта
 */
export const postApiUserChangeUserSettings = (
    changeUserSettingsDto: ChangeUserSettingsDto,
 ) => {
      return useFetchMutator<UserSettings>(
      {url: `/api/user/change-user-settings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeUserSettingsDto
    },
      );
    }
  export type PostApiUserCreateResult = NonNullable<Awaited<ReturnType<typeof postApiUserCreate>>>
export type GetApiUserGetSharedItemsUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetSharedItemsUserId>>>
export type PostApiUserRemoveSharedItemResult = NonNullable<Awaited<ReturnType<typeof postApiUserRemoveSharedItem>>>
export type GetApiUserGetPlanetsUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetPlanetsUserId>>>
export type GetApiUserGetAllSettingsResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetAllSettings>>>
export type GetApiUserGetUserSettingsUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetUserSettingsUserId>>>
export type PostApiUserChangeUserSettingsResult = NonNullable<Awaited<ReturnType<typeof postApiUserChangeUserSettings>>>
