/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  CreateBuildingDto,
  GetPlanetResponseDto
} from '../../models';

import { useFetchMutator } from '../../../api/index';



  /**
 * @summary Получение планеты по Id
 */
export const getApiPlanetId = (
    id: number,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Добавить здание в очередь строительства (стройка или удаление, в зависимости от типа операции).
 */
export const postApiPlanetBuildingOperation = (
    createBuildingDto: CreateBuildingDto,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/building-operation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBuildingDto
    },
      );
    }
  export type GetApiPlanetIdResult = NonNullable<Awaited<ReturnType<typeof getApiPlanetId>>>
export type PostApiPlanetBuildingOperationResult = NonNullable<Awaited<ReturnType<typeof postApiPlanetBuildingOperation>>>
