/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  ChangeBuildingEfficiencyDto,
  CreateBuildingDto,
  GameBuildingsResponseDto,
  GetPlanetResponseDto,
  PlanetIndustriesDto,
  RemoveFromPlanetStoreDto,
  RemoveFromQueueDto
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  /**
 * @summary Получение планеты по Id
 */
export const getApiPlanetId = (
    id: number,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Добавить здание в очередь строительства (стройка или удаление, в зависимости от типа операции).
 */
export const postApiPlanetBuildingOperation = (
    createBuildingDto: CreateBuildingDto,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/building-operation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBuildingDto
    },
      );
    }
  /**
 * @summary Изменение эффективности работы здания
 */
export const postApiPlanetChangeBuildingEfficiency = (
    changeBuildingEfficiencyDto: ChangeBuildingEfficiencyDto,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/change-building-efficiency`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeBuildingEfficiencyDto
    },
      );
    }
  /**
 * @summary Удаление здания из очереди строительства
 */
export const postApiPlanetBuildingOperationRemoveFromQueue = (
    removeFromQueueDto: RemoveFromQueueDto,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/building-operation/remove-from-queue`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeFromQueueDto
    },
      );
    }
  /**
 * @summary Удаление со склада планеты любой вещи
 */
export const postApiPlanetRemoveFromStorage = (
    removeFromPlanetStoreDto: RemoveFromPlanetStoreDto,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/remove-from-storage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeFromPlanetStoreDto
    },
      );
    }
  /**
 * @summary Получение всех возможных зданий для постройки на планете
 */
export const getApiPlanetGetAllBuildingsInfo = (
    
 ) => {
      return useFetchMutator<GameBuildingsResponseDto>(
      {url: `/api/planet/get-all-buildings-info`, method: 'GET'
    },
      );
    }
  /**
 * @summary Получение планеты по айди пользователя и названию планеты
 */
export const getApiPlanetByNameUserIdPlanetName = (
    userId: number,
    planetName: string,
 ) => {
      return useFetchMutator<GetPlanetResponseDto>(
      {url: `/api/planet/by-name/${userId}/${planetName}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Получение производств планеты по айди
 */
export const getApiPlanetIndustriesPowerPlanetId = (
    planetId: number,
 ) => {
      return useFetchMutator<PlanetIndustriesDto>(
      {url: `/api/planet/industries-power/${planetId}`, method: 'GET'
    },
      );
    }
  export type GetApiPlanetIdResult = NonNullable<Awaited<ReturnType<typeof getApiPlanetId>>>
export type PostApiPlanetBuildingOperationResult = NonNullable<Awaited<ReturnType<typeof postApiPlanetBuildingOperation>>>
export type PostApiPlanetChangeBuildingEfficiencyResult = NonNullable<Awaited<ReturnType<typeof postApiPlanetChangeBuildingEfficiency>>>
export type PostApiPlanetBuildingOperationRemoveFromQueueResult = NonNullable<Awaited<ReturnType<typeof postApiPlanetBuildingOperationRemoveFromQueue>>>
export type PostApiPlanetRemoveFromStorageResult = NonNullable<Awaited<ReturnType<typeof postApiPlanetRemoveFromStorage>>>
export type GetApiPlanetGetAllBuildingsInfoResult = NonNullable<Awaited<ReturnType<typeof getApiPlanetGetAllBuildingsInfo>>>
export type GetApiPlanetByNameUserIdPlanetNameResult = NonNullable<Awaited<ReturnType<typeof getApiPlanetByNameUserIdPlanetName>>>
export type GetApiPlanetIndustriesPowerPlanetIdResult = NonNullable<Awaited<ReturnType<typeof getApiPlanetIndustriesPowerPlanetId>>>
