/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  ChangeSpeedPercentForTechDto,
  RequiredTech,
  UserTechnologyQueueCreateDto,
  UserTechnologyQueueResponseDto
} from '../../models';

import { useFetchMutator } from '../../../mutator/index';



  /**
 * @summary Получение текущей очереди исследований для указанного пользователя
 */
export const getApiUserTechGetTechQueueUserId = (
    userId: number,
 ) => {
      return useFetchMutator<UserTechnologyQueueResponseDto[]>(
      {url: `/api/user-tech/get-tech-queue/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Добавление новой технологии в очередь исследований пользователя
 */
export const postApiUserTechAddToQueue = (
    userTechnologyQueueCreateDto: UserTechnologyQueueCreateDto,
 ) => {
      return useFetchMutator<UserTechnologyQueueResponseDto[]>(
      {url: `/api/user-tech/add-to-queue`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userTechnologyQueueCreateDto
    },
      );
    }
  /**
 * @summary Получение дерева зависимостей (родительских технологий) для изучения конкретной технологии до определенного уровня
 */
export const getApiUserTechGetTechTreeForTechInnerIdRequiredLevelUserId = (
    techInnerId: number,
    requiredLevel: number,
    userId: number,
 ) => {
      return useFetchMutator<RequiredTech[]>(
      {url: `/api/user-tech/get-tech-tree-for/${techInnerId}/${requiredLevel}/${userId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Изменение процента скорости исследований для конкретной технологии в очереди
 */
export const putApiUserTechChangeTechSpeedPercentInQueue = (
    changeSpeedPercentForTechDto: ChangeSpeedPercentForTechDto,
 ) => {
      return useFetchMutator<UserTechnologyQueueResponseDto[]>(
      {url: `/api/user-tech/change-tech-speed-percent-in-queue`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changeSpeedPercentForTechDto
    },
      );
    }
  export type GetApiUserTechGetTechQueueUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserTechGetTechQueueUserId>>>
export type PostApiUserTechAddToQueueResult = NonNullable<Awaited<ReturnType<typeof postApiUserTechAddToQueue>>>
export type GetApiUserTechGetTechTreeForTechInnerIdRequiredLevelUserIdResult = NonNullable<Awaited<ReturnType<typeof getApiUserTechGetTechTreeForTechInnerIdRequiredLevelUserId>>>
export type PutApiUserTechChangeTechSpeedPercentInQueueResult = NonNullable<Awaited<ReturnType<typeof putApiUserTechChangeTechSpeedPercentInQueue>>>
