import {ref} from "vue";

export type SessionLog = {
    planetName: string,
    eventType: string,
    count: number,
    buildingType: string,
    text: string
}

export const _SessionLogs = ref<SessionLog[]>([
    // {text: '1 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '2 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '3 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
    // {text: '5 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, iusto!'},
])