/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * OpenAPI spec version: v1
 */
import type {
  LoginUserRequestDto,
  LoginUserResponseDto,
  RefreshTokenDto,
  RefreshTokenResponse
} from '../../models';

import { useFetchMutator } from '@/mutator/index';



  /**
 * @summary Обновление токенов.
 */
export const postApiAuthTokensRefresh = (
    refreshTokenDto: RefreshTokenDto,
 ) => {
      return useFetchMutator<RefreshTokenResponse>(
      {url: `/api/auth/tokens/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenDto
    },
      );
    }
  /**
 * @summary Авторизация пользователя по логину/паролю.
 */
export const postApiAuthLogin = (
    loginUserRequestDto: LoginUserRequestDto,
 ) => {
      return useFetchMutator<LoginUserResponseDto>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginUserRequestDto
    },
      );
    }
  export type PostApiAuthTokensRefreshResult = NonNullable<Awaited<ReturnType<typeof postApiAuthTokensRefresh>>>
export type PostApiAuthLoginResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
